baseURL: "https://valdirnp.dev/"
languageCode: "pt-br"
title: "Valdir Pereira"
theme: "toha"

defaultContentLanguage: br

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

enableEmoji: true

params:
  background: "images/default-background.jpg"

  logo:
    main: assets/images/main-logo.png
    inverted: assets/images/inverted-logo.png
    favicon: assets/images/inverted-logo.png

  # gitRepo: https://github.com/valdirnp/valdirnp

  enableBlogPost: true

  enableTOC: false

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false