baseURL = "https://valdirnp.com.br/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "pt-br"
language = "pt-br"
theme = "vncnt-hugo"
title = "Valdir Pereira"

[blackfriday]
    extensions = ["hardLineBreak"]

[permalinks]
    fixed = ":title/"
    posts = "posts/:slug/"

[params]
    title = "Valdir Pereira"
    author = "Valdir Pereira"
    email = "valdiriano@gmail.com"
    firstName = "Valdir"
    lastName = "Pereira"
    address = "São Paulo, BR"
    description = "Back-End Developer and Software Engineer."
    bio = "Back-End Developer.\nSoftware Engineer."
    avatar = "img/avatar.jpg"
    favicon = "img/favicon.ico"
    error404 = "Well, I think you've gone too far, pal."

    [params.contact]
        github = "https://github.com/ValdirNp"
        instagram = "https://instagram.com/valdirnasp"
        twitter = "https://twitter.com/valdirnp"
